---
deployment:
  tasks:
    - export SRCPATH=/home/bss717sst0rg/repositories/717bss.com
    - export DEPLOYPATH=/home/bss717sst0rg/public_html
    - /bin/mkdir -p $DEPLOYPATH/images
    - /bin/cp $SRCPATH/index.html $DEPLOYPATH/
    - /bin/cp $SRCPATH/style.css $DEPLOYPATH/
    - /bin/cp $SRCPATH/.htaccess $DEPLOYPATH/
    - /bin/cp $SRCPATH/favicon.ico $DEPLOYPATH/
    - /bin/cp $SRCPATH/favicon.svg $DEPLOYPATH/
    - /bin/cp $SRCPATH/favicon-96x96.png $DEPLOYPATH/
    - /bin/cp $SRCPATH/apple-touch-icon.png $DEPLOYPATH/
    - /bin/cp $SRCPATH/site.webmanifest $DEPLOYPATH/
    - /bin/cp $SRCPATH/web-app-manifest-192x192.png $DEPLOYPATH/
    - /bin/cp $SRCPATH/web-app-manifest-512x512.png $DEPLOYPATH/
    - /bin/cp $SRCPATH/images/* $DEPLOYPATH/images/
